org: j41r0
service: clinic-project-backend


provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - events:*
          Resource: "*"

functions:
# Patient CRUD functions
  patientsCreate:
    handler: src/patients/functions/create.handler
    events:
      - http:
          method: POST
          path: patients

  patientsRead:
    handler: src/patients/functions/read.findHandler
    events:
      - http:
          method: GET
          path: patients/allPatients
        
  patientReadById:
    handler: src/patients/functions/read.findByIdHandler
    events:
      - http:
          method: GET
          path: patient/{id}
  
  patientDelete:
    handler: src/patients/functions/delete.handler
    events:
      - http:
          method: DELETE
          path: patient/{id}

  patientsPatch:
    handler: src/patients/functions/patch.handler
    events:
      - http:
          method: PATCH
          path: patients/{id}

# Patients Mail Sender Functions
  patientsMailSender:
    handler: src/patients/others/mailSender.handler
    events:
      - eventBridge:
        pattern:
        source:
          - "aula5-clinica"
        detail-type:
          - "PatientCreated"

  # Sign Up Function

  signUp:
    handler: src/auth/signUp.handler
    events:
      - http:
          method: POST
          path: signUp

  confirmSighUp:
    handler: src/auth/signUp.confirmationHandler
    events:
      - http:
          method: POST
          path: confirmSighUp

# Patients Table
resources:
  Resources:
    patientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PatientTable
        AttributeDefinitions:
          - AttributeName: PK #taxId
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
